In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 🔹 Array Creation & Basics

1. Create a 1D NumPy array with values from 0 to 9.
   

In [5]:
array1 = np.arange(0,10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


2. Create a 2D array with values from 1 to 9 (3x3).

In [12]:
array2 = np.arange(1,10)
print(array2)

array2_reshaped = array2.reshape(3,3)
print(f"Reshaped Array \n{array2_reshaped}")

[1 2 3 4 5 6 7 8 9]
Reshaped Array 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Create an array of all zeros with size 10.

In [13]:
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. Create an array of all ones with size 7.

In [14]:
array_ones = np.ones(7)
array_ones

array([1., 1., 1., 1., 1., 1., 1.])

5. Create an array filled with the number 5 of size 6.

 

In [18]:
array_full = np.full(6,5)
array_full

array([5, 5, 5, 5, 5, 5])

6. Create a sequence of numbers from 10 to 50 with a step of 5.

In [19]:
array_arange = np.arange(10,51,5)
array_arange

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

7. Create an array of 15 random integers between 1 and 100.

In [22]:
import random
array_random = np.random.randint(1,100, size=15)
array_random

array([39, 56, 85, 85, 31,  5, 50, 89, 33,  6, 45, 86, 55, 82, 87],
      dtype=int32)

8. Create an identity matrix of size 4x4.

In [24]:
array_identity = np.eye(4)
array_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

9. Create a 1D array of 20 equally spaced points between 0 and 1.

In [25]:
array_linspace = np.linspace(0,1,20)
array_linspace

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

10. Generate an array of 10 random floats between 0 and 1.

In [27]:
array_randomfloats = np.random.rand(10)

array_randomfloats

array([0.86046024, 0.55422271, 0.29239332, 0.40334139, 0.64258867,
       0.60705175, 0.29243936, 0.62767745, 0.31385113, 0.79799406])

# 🔹 Array Properties



1. Find the shape, size, and data type of a NumPy array.

In [35]:
array_test = np.array([[1,2,3,4,5],
                      [6,7,8,9,10],
                      [11,12,13,14,15],
                      [16,17,18,19,20]])
print(array_test)
print("Shape :",array_test.shape)
print("Size :", array_test.size)
print("Data Type :", array_test.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape : (4, 5)
Size : 20
Data Type : int64


2. Check the number of dimensions of a given array.


In [38]:
array_test2 = np.array([[[np.arange(1,6)],
                       [np.arange(6,11)]],
                      [[np.arange(11,16)],
                       [np.arange(16,21)]]])

print(array_test2)
print("Dimension :",array_test2.ndim)

[[[[ 1  2  3  4  5]]

  [[ 6  7  8  9 10]]]


 [[[11 12 13 14 15]]

  [[16 17 18 19 20]]]]
Dimension : 4


3. Change the data type of an array to float.

In [40]:
changed_datatype = array_test.astype("float")
changed_datatype.dtype

dtype('float64')

4. Reshape a 1D array of 12 elements into a 3x4 2D array.


In [44]:
array_1D = np.arange(12).reshape((3,4))
array_1D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

5. Flatten a 2D array to 1D.


In [45]:
flattened_array = array_1D.flatten()

flattened_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

6. Create a 3x3 array and print its transpose.


In [46]:
array_test_transpose = array_test.transpose()
array_test_transpose

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

7. Convert a list of lists into a NumPy array.


In [48]:
list_of_lists = [[0,0,1],[0,1,0],[1,0,0]]
numpy_array = np.array(list_of_lists)

print(numpy_array)

[[0 0 1]
 [0 1 0]
 [1 0 0]]


8. Check if a given variable is a NumPy array or not.


In [50]:
a = np.array([1,2,3,4,5])

is_array = isinstance(a,np.ndarray)
print(is_array)

True


9.  Copy an array using copy() and show it is not linked to the original.


In [54]:
original = np.array([9,8,7,6,5,4,3,2,1,0])

copied = original.copy()
copied[1]= 0
print("Original Array : ",original)
print("Copied Array : ",copied)

Original Array :  [9 8 7 6 5 4 3 2 1 0]
Copied Array :  [9 0 7 6 5 4 3 2 1 0]


10. Use np.full() to create a 4x4 array filled with the number 9.

In [55]:
tensor_array = np.full((4,4),9)
print(tensor_array)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


# 🔹 Indexing and Slicing

1. Extract the 2nd row from a 2D array.

In [58]:
array_2D = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(array_2D[1])

[4 5 6]


2. Extract the 3rd column from a 2D array.

In [59]:
print(array_2D[:,2])

[3 6 9]


3. Get a subarray (middle 3x3) from a 5x5 matrix.

In [64]:
array_5D = np.arange(0,25).reshape((5,5))
print(array_5D)

middle_array = array_5D[1:4,1:4]
print("Subarray :\n",middle_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Subarray :
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


4. Slice the last 3 elements from a 1D array.


In [71]:
array_1D = np.arange(1,11)
print(array_1D)

print("Last 3 elements :\n", array_1D[[-1,-2,-3]])

[ 1  2  3  4  5  6  7  8  9 10]
Last 3 elements :
 [10  9  8]


5. Reverse a 1D NumPy array.

In [79]:
array_reverse = array_1D[::-1]
print(array_reverse)

[10  9  8  7  6  5  4  3  2  1]


6. Set the first 3 elements of an array to 100.

In [80]:
array_1D[:3]=100
array_1D

array([100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

7. Replace all even numbers in an array with -1.

In [82]:
no_array = np.arange(1,21)
print(no_array)

no_array[no_array %2==0] = -1
print(no_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


8. Select only the odd elements from an array.

In [87]:
not_array = np.arange(1,21)
odd_array = not_array[not_array%2 != 0]
print(odd_array)

[ 1  3  5  7  9 11 13 15 17 19]


9. Find the positions of elements greater than 50 in an array.

In [93]:
choose = np.random.randint(1,100, size=15)
print(choose)

postion = np.where(choose>50)
print(postion[0])

[44 77 88  9 46 86 31 41 83 96 35 54 16 35 45]
[ 1  2  5  8  9 11]


10.  Select a diagonal from a 2D square array.

In [94]:
array_3d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
diagonal = np.diag(array_3d)
print(diagonal)

[1 5 9]


# 🔹 Mathematical Operations

1. Perform element-wise addition of two same-size arrays.

In [3]:
arr1 = np.array([12,56,58,25,23])
arr2 = np.array([98,65,75,2,47])

added_arrays = arr1 + arr2
print(added_arrays)

[110 121 133  27  70]


2.  Perform element-wise multiplication.

In [4]:
multiplied_arrays = arr1 * arr2
print(multiplied_arrays)

[1176 3640 4350   50 1081]


3. Multiply a 1D array by a scalar (e.g., 5).


In [5]:
array_D = np.array([5,10,15,20,25])
scalar_multiply = array_D * 5

print(scalar_multiply)

[ 25  50  75 100 125]


4. Compute the sum of all elements in an array.

In [7]:
array_sum = np.array([50,25,5,65,45])
sum_of_elements = array_sum.sum()

print("Sum of all elements of array :",sum_of_elements)

Sum of all elements of array : 190


5. Compute the row-wise and column-wise sums of a 2D array.

In [15]:
matrix = np.array([[5,25,50],
                  [6,26,51],
                  [7,27,52]])


row_wise_sum = np.sum(matrix, axis=1)
col_wise_sum = np.sum(matrix, axis=0)

print("Matrix :\n",matrix)
print("Row Wise Addition :",row_wise_sum)
print("Column Wise Addition :",col_wise_sum)

Matrix :
 [[ 5 25 50]
 [ 6 26 51]
 [ 7 27 52]]
Row Wise Addition : [80 83 86]
Column Wise Addition : [ 18  78 153]


6. Find the max, min, mean, and standard deviation of an array.

In [21]:
array_describe = np.array(np.arange(25,70,7))
max_no = array_describe.max()
min_no = array_describe.min()
mean = array_describe.mean()
std_array = array_describe.std()


print("Array :",array_describe)
print("Maximun :",max_no)
print("Minimun :",min_no)
print("Mean of Array :",mean)
print("Standard Deviation :",std_array)


Array : [25 32 39 46 53 60 67]
Maximun : 67
Minimun : 25
Mean of Array : 46.0
Standard Deviation : 14.0


7. Normalize a NumPy array (values between 0 and 1).

In [27]:
import random
elements = np.random.randint(20,100, size=8)
elements_2D = np.array([[5,25,50],
                  [6,26,51],
                  [7,27,52]])

print("Array :",elements)

normalized_Array = ((elements - elements.min()) / (elements.max() - elements.min()))
normalized_2D_Array = ((elements_2D - elements_2D.min()) / (elements_2D.max() - elements_2D.min()))

print("Normalized Array :",normalized_Array)
print("Normalized 2D Array :\n",normalized_2D_Array)



Array : [89 35 23 75 67 60 55 82]
Normalized Array : [1.         0.18181818 0.         0.78787879 0.66666667 0.56060606
 0.48484848 0.89393939]
Normalized 2D Array :
 [[0.         0.42553191 0.95744681]
 [0.0212766  0.44680851 0.9787234 ]
 [0.04255319 0.46808511 1.        ]]


8. Square only the even elements in an array.

In [13]:
element = np.arange(1,21)
sq_elements = element[element%2==0]
squared_num = sq_elements ** 2
print("Original Array :",element)
print("Even Numbers :",sq_elements)
print("Square Of Even numbers :",squared_num)

Original Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even Numbers : [ 2  4  6  8 10 12 14 16 18 20]
Square Of Even numbers : [  4  16  36  64 100 144 196 256 324 400]


9. Use np.where() to replace all values > 10 with 0.

In [16]:
num = element.copy()
replaced_num = np.where(num>10,0,num)
print(replaced_num)

[ 1  2  3  4  5  6  7  8  9 10  0  0  0  0  0  0  0  0  0  0]


10. Use broadcasting to subtract the mean from each row in a 2D array.

In [21]:
array_with_2D = np.arange(0,9).reshape((3,3))
mean = array_with_2D.mean()
mean_subtracted_Array = array_with_2D - mean
print(mean_subtracted_Array)

[[-4. -3. -2.]
 [-1.  0.  1.]
 [ 2.  3.  4.]]


# 🔹 Random and Sorting


1. Generate a 1D array of 8 random integers between 10 and 99.

2. Shuffle the elements of an array randomly.

3. Sort a NumPy array in ascending order.

4. Sort a 2D array by a specific row or column.

5. Set a random seed and generate reproducible random numbers.

# 🔹 Advanced Basics

1. Stack two 1D arrays horizontally and vertically.

2. Split an array into 3 equal parts using np.split().

3. Use np.unique() to find unique values in an array.

4. Use np.intersect1d() and np.setdiff1d() on two arrays.

5. Create a boolean mask where all values > 50 are True.